---
include:
  - board: nice_nano@2//zmk
    shield: crosses_left
    artifact-name: crosses_36_left
  - board: nice_nano@2//zmk
    shield: crosses_right
    artifact-name: crosses_36_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: crosses_dongle dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y
    artifact-name: crosses_dongle_studio
