---
include:
  - board: nice_nano@2//zmk
    shield: crosses_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: crosses_36_left
  - board: nice_nano@2//zmk
    shield: crosses_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: crosses_36_right
  - board: xiao_ble//zmk
    shield: crosses_dongle dongle_screen
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y
    artifact-name: crosses_dongle_studio
  - board: nice_nano@2//zmk
    shield: settings_reset
    artifact-name: settings_reset_left_right
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset_dongle
